/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutWorkstationRouteImport } from './routes/_layout/workstation'
import { Route as LayoutStickersRouteImport } from './routes/_layout/stickers'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutCctvRouteImport } from './routes/_layout/cctv'
import { Route as LayoutAccessRouteImport } from './routes/_layout/access'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWorkstationRoute = LayoutWorkstationRouteImport.update({
  id: '/workstation',
  path: '/workstation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStickersRoute = LayoutStickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCctvRoute = LayoutCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccessRoute = LayoutAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof LayoutAccessRoute
  '/cctv': typeof LayoutCctvRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/stickers': typeof LayoutStickersRoute
  '/workstation': typeof LayoutWorkstationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof LayoutAccessRoute
  '/cctv': typeof LayoutCctvRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/profile': typeof LayoutProfileRoute
  '/stickers': typeof LayoutStickersRoute
  '/workstation': typeof LayoutWorkstationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/access': typeof LayoutAccessRoute
  '/_layout/cctv': typeof LayoutCctvRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/stickers': typeof LayoutStickersRoute
  '/_layout/workstation': typeof LayoutWorkstationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/cctv'
    | '/dashboard'
    | '/profile'
    | '/stickers'
    | '/workstation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access'
    | '/cctv'
    | '/dashboard'
    | '/profile'
    | '/stickers'
    | '/workstation'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/access'
    | '/_layout/cctv'
    | '/_layout/dashboard'
    | '/_layout/profile'
    | '/_layout/stickers'
    | '/_layout/workstation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/workstation': {
      id: '/_layout/workstation'
      path: '/workstation'
      fullPath: '/workstation'
      preLoaderRoute: typeof LayoutWorkstationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stickers': {
      id: '/_layout/stickers'
      path: '/stickers'
      fullPath: '/stickers'
      preLoaderRoute: typeof LayoutStickersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cctv': {
      id: '/_layout/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof LayoutCctvRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/access': {
      id: '/_layout/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof LayoutAccessRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAccessRoute: typeof LayoutAccessRoute
  LayoutCctvRoute: typeof LayoutCctvRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutStickersRoute: typeof LayoutStickersRoute
  LayoutWorkstationRoute: typeof LayoutWorkstationRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccessRoute: LayoutAccessRoute,
  LayoutCctvRoute: LayoutCctvRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutStickersRoute: LayoutStickersRoute,
  LayoutWorkstationRoute: LayoutWorkstationRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
